version: '3.8'

networks:
  backend-network:
    driver: bridge

services:
  ########################
  #  API Gateway Service #
  ########################
  api-gateway:
    build:
      context: ./API-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - backend-network
    depends_on:
      - user-service
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://admin:hw445Rl1pEAXqhti@cluster-1-shard-00-00.rylgk.mongodb.net:27017,cluster-1-shard-00-01.rylgk.mongodb.net:27017,cluster-1-shard-00-02.rylgk.mongodb.net:27017/user-database?ssl=true&replicaSet=atlas-xyz-shard-0&authSource=admin&retryWrites=true&w=majority"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  ######################
  #  User-Service      #
  ######################
  user-service:
    build:
      context: ./user-service/user-service
      dockerfile: Dockerfile
    container_name: user-service
    expose:
      - "8081"
    networks:
      - backend-network
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://admin:hw445Rl1pEAXqhti@cluster-1-shard-00-00.rylgk.mongodb.net:27017,cluster-1-shard-00-01.rylgk.mongodb.net:27017,cluster-1-shard-00-02.rylgk.mongodb.net:27017/user-database?ssl=true&replicaSet=atlas-xyz-shard-0&authSource=admin&retryWrites=true&w=majority"
    dns:
      - 8.8.8.8
      - 8.8.4.4
